### ISSUE TITLE
Bot position undefined.

### ISSUE THREAD

**Issue by skyrawr** [Karang/mineflayer-pathfinder#3]
const b = this.bot.blockAt(new Vec3(pos.x + dx, pos.y + dy, pos.z + dz))
                                            ^

TypeError: Cannot read property 'x' of undefined
    at Movements.getBlock (C:\Users\Sky\Desktop\Projects\navigate\path\lib\movements.js:39:45)
    at Movements.safeToBreak (C:\Users\Sky\Desktop\Projects\navigate\path\lib\movements.js:56:16)
    at Movements.safeOrBreak (C:\Users\Sky\Desktop\Projects\navigate\path\lib\movements.js:68:15)
    at Movements.getMoveForward (C:\Users\Sky\Desktop\Projects\navigate\path\lib\movements.js:134:18)
    at Movements.getNeighbors (C:\Users\Sky\Desktop\Projects\navigate\path\lib\movements.js:269:12)
    at astar (C:\Users\Sky\Desktop\Projects\navigate\path\lib\astar.js:60:33)
    at Object.bot.pathfinder.getPathTo (C:\Users\Raul\Desktop\Projects\navigate\path\index.js:61:5)
    at Timeout.monitorMovement [as _onTimeout] (C:\Users\Sky\Desktop\Projects\navigate\path\index.js:116:24)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

this happens every 2-3 hours while pathfinding, and stops the bot.

**Comment by Karang** [comment]
I think I know why this could happen. I've committed a fix. Try again with latest version and reopen if the bug is still here.
