### ISSUE TITLE
TypeError: Cannot read property 'shapes' of null

### ISSUE THREAD

**Issue by werymanen** [Karang/mineflayer-pathfinder#36]
# Error 
```
/mnt/dev/murderer/node_modules/mineflayer-pathfinder/index.js:103
    if (block.shapes.length === 0) return null
              ^

TypeError: Cannot read property 'shapes' of null
    at getPositionOnTopOf (/mnt/dev/murderer/node_modules/mineflayer-pathfinder/index.js:103:15)
    at Bot.monitorMovement (/mnt/dev/murderer/node_modules/mineflayer-pathfinder/index.js:266:14)
    at Bot.emit (events.js:315:20)
    at Timeout.doPhysics [as _onTimeout] (/mnt/dev/murderer/node_modules/mineflayer/lib/plugins/physics.js:62:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

# About
Hi there, I have an issue with the pathfinder.
I am working on a bot that kills players. The way I went about making this is on spawning I've set an interval every 500ms to setGoal to the player's current position. It worked just fine, but when I kill the bot, it throws an error.

What can I do about it?

**Comment by werymanen** [comment]
It doesn't always happen, I don't know why

**Comment by rom1504** [comment]
@Karang shouldn't the code check each return of blockAt whether it's null
or not ?
Are there cases where it's guaranteed that blockAt will return non null in
pathfinder ?

**Comment by Karang** [comment]
I think what happens there is that the bot have a path in a loaded chunk, but when it dies, it unload the chunks but keep trying to follow the path in the now unloaded chunk. Some null check can be added and in this case resetting the path seems a good solution.
