### ISSUE TITLE
i can't run the test.js

### ISSUE THREAD

**Issue by hutu13879513663** [Karang/mineflayer-pathfinder#46]
# node test.js 
/root/mineflayer-pathfinder/node_modules/protodef/src/compiler.js:157
    for (const [type, [kind, fn]] of Object.entries(types)) {
                                            ^

TypeError: Object.entries is not a function
    at ReadCompiler.addTypes (/root/mineflayer-pathfinder/node_modules/protodef/src/compiler.js:157:45)
    at new ReadCompiler (/root/mineflayer-pathfinder/node_modules/protodef/src/compiler.js:253:10)
    at new ProtoDefCompiler (/root/mineflayer-pathfinder/node_modules/protodef/src/compiler.js:12:25)
    at createProto (/root/mineflayer-pathfinder/node_modules/prismarine-nbt/nbt.js:9:20)
    at Object.<anonymous> (/root/mineflayer-pathfinder/node_modules/prismarine-nbt/nbt.js:15:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
How to fix it

**Comment by Karang** [comment]
Update your node version
